version: "3.9"

services:
  # Production environment

  server:
    container_name: server
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile.server
      target: server
    env_file:
      - ../.env.production
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - prod-net
      - proxy-network
    profiles:
      - production

networks:
  queue-net:
    driver: bridge
  prod-net:
    driver: bridge
  proxy-network:
    external: true
